# Copyright 2015 OpenStack Foundation
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

"""fortinet_ml2

Revision ID: 1361f3eff452
Revises: 544673ac99ab
Create Date: 2015-06-19 18:16:22.123644

"""

# revision identifiers, used by Alembic.
revision = '1361f3eff452'
down_revision = '544673ac99ab'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fortinet_ml2_subnets')
    op.drop_table('fortinet_vlink_vlan_allocations')
    op.drop_table('fortinet_static_routers')
    op.drop_table('fortinet_vlink_ip_allocations')
    op.drop_table('fortinet_ml2_namespaces')
    op.drop_table('fortinet_ml2_reservedips')
    ### end Alembic commands ###


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fortinet_ml2_reservedips',
    sa.Column('port_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('subnet_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('mac', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('vdom_name', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('edit_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('port_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('fortinet_ml2_namespaces',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('tenant_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('vdom_name', mysql.VARCHAR(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id', 'tenant_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('fortinet_vlink_ip_allocations',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('ip_int_vdom', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('ip_ext_vdom', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('vlan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('allocated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('fortinet_static_routers',
    sa.Column('subnet_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('vdom_name', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('edit_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('subnet_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('fortinet_vlink_vlan_allocations',
    sa.Column('vlan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('vdom_name', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('inf_name_int_vdom', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('inf_name_ext_vdom', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('allocated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('vlan_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('fortinet_ml2_subnets',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('subnet_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('vdom_name', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('mkey', mysql.VARCHAR(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id', 'subnet_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
