# Copyright 2015 OpenStack Foundation
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

"""fortinet ml2 l3

Revision ID: 21f2acac5619
Revises: 544673ac99ab
Create Date: 2015-07-18 00:50:16.302498

"""

# revision identifiers, used by Alembic.
revision = '21f2acac5619'
down_revision = '544673ac99ab'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'fortinet_vlink_ip_allocations')
    op.drop_table(u'fortinet_ml2_reservedips')
    op.drop_table(u'fortinet_ml2_namespaces')
    op.drop_table(u'fortinet_vlink_vlan_allocations')
    op.drop_table(u'fortinet_ml2_subnets')
    op.drop_table(u'fortinet_firewall_policies')
    op.drop_table(u'fortinet_floatingip_allocations')
    op.drop_table(u'fortinet_static_routers')
    ### end Alembic commands ###


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'fortinet_static_routers',
    sa.Column(u'subnet_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column(u'vdom_name', mysql.VARCHAR(length=11), nullable=True),
    sa.Column(u'edit_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'subnet_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table(u'fortinet_floatingip_allocations',
    sa.Column(u'ip_subnet', mysql.VARCHAR(length=32), server_default=sa.text(u"''"), nullable=False),
    sa.Column(u'vdom_name', mysql.VARCHAR(length=11), nullable=True),
    sa.Column(u'floating_ip_address', mysql.VARCHAR(length=36), nullable=True),
    sa.Column(u'vip_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column(u'allocated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column(u'bound', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'ip_subnet'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table(u'fortinet_firewall_policies',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'vdom_name', mysql.VARCHAR(length=11), nullable=True),
    sa.Column(u'srcintf', mysql.VARCHAR(length=11), nullable=True),
    sa.Column(u'dstintf', mysql.VARCHAR(length=11), nullable=True),
    sa.Column(u'srcaddr', mysql.VARCHAR(length=32), server_default=sa.text(u"'all'"), nullable=True),
    sa.Column(u'dstaddr', mysql.VARCHAR(length=32), server_default=sa.text(u"'all'"), nullable=True),
    sa.Column(u'edit_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table(u'fortinet_ml2_subnets',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'subnet_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column(u'vdom_name', mysql.VARCHAR(length=11), nullable=False),
    sa.Column(u'mkey', mysql.VARCHAR(length=11), nullable=True),
    sa.PrimaryKeyConstraint(u'id', u'subnet_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table(u'fortinet_vlink_vlan_allocations',
    sa.Column(u'vlan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column(u'vdom_name', mysql.VARCHAR(length=11), nullable=True),
    sa.Column(u'inf_name_int_vdom', mysql.VARCHAR(length=11), nullable=True),
    sa.Column(u'inf_name_ext_vdom', mysql.VARCHAR(length=11), nullable=True),
    sa.Column(u'allocated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'vlan_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table(u'fortinet_ml2_namespaces',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'tenant_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column(u'vdom_name', mysql.VARCHAR(length=11), nullable=True),
    sa.PrimaryKeyConstraint(u'id', u'tenant_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table(u'fortinet_ml2_reservedips',
    sa.Column(u'port_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column(u'subnet_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column(u'mac', mysql.VARCHAR(length=32), nullable=False),
    sa.Column(u'ip', mysql.VARCHAR(length=32), nullable=False),
    sa.Column(u'vdom_name', mysql.VARCHAR(length=11), nullable=True),
    sa.Column(u'edit_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'port_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table(u'fortinet_vlink_ip_allocations',
    sa.Column(u'vlink_ip_subnet', mysql.VARCHAR(length=32), server_default=sa.text(u"''"), nullable=False),
    sa.Column(u'vdom_name', mysql.VARCHAR(length=11), nullable=True),
    sa.Column(u'vlan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column(u'allocated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'vlink_ip_subnet'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
